/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainDialog.java
 *
 * Created on Aug 23, 2010, 1:14:18 PM
 */

package KMLParser;
import de.micromata.opengis.kml.v_2_2_0.Coordinate;
import de.micromata.opengis.kml.v_2_2_0.Document;
import de.micromata.opengis.kml.v_2_2_0.Kml;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

class Utils {

    public final static String kml = "kml";

    /*
     * Get the extension of a file.
     */
    public static String getExtension(File f) {
        String ext = null;
        String s = f.getName();
        int i = s.lastIndexOf('.');

        if (i > 0 &&  i < s.length() - 1) {
            ext = s.substring(i+1).toLowerCase();
        }
        return ext;
    }
}


/**
 *
 * @author admin
 */
public class MainDialog extends javax.swing.JFrame {

    Kml kml;
    KML_StyleManager kmlStyleManager;

    /** Creates new form MainDialog */
    public MainDialog() {
        initComponents();

        this.parseByIconJPanel.setVisible(false);
        this.kmlStyleManager = new KML_StyleManager(30, 30);
        this.parseByIconJPanel.setKMLStyleManager(kmlStyleManager);
        this.EditKMLButton.setVisible(false);
        this.textlAddButton.setVisible(false);
        this.StyleSplitterlButton.setVisible(false);
        this.parseByIconJPanel.setVisible(false);
        this.KMLViewJPanel.setVisible(false);
        this.CalculatePointslButton.setVisible(false);
        this.KMLCalculatePoints.setVisible(false);
        this.texAddtJPanel.setVisible(false);

/*

        Coordinate c1 = new Coordinate(-64.24600363095102, -35.0336359422789);
        Coordinate c2 = new Coordinate(-64.24773575391606, -35.03383092961178);
        Coordinate p  = new Coordinate(-64.24599590678973, -35.03366163321364);

        p = new Coordinate(-64.246223, -35.033662);
        double b = CoordinateCalculator.getBearing(c1, c2);

        double b1 = ((b - 90) + 360) % 360;
        double b2 = ((b + 90) + 360) % 360;

        Coordinate rC1 = CoordinateCalculator.intersection(c1, b, p, b1);
        Coordinate rC2 = CoordinateCalculator.intersection(c1, b, p, b2);


       // Coordinate i =   CoordinateCalculator.getCoordinateInterception(cS, cE, p);

        int a;*/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        OpenFileButton = new javax.swing.JButton();
        OpenedFilePathjLabel = new javax.swing.JLabel();
        parseByIconJPanel = new KMLParser.ParseByIconJPanel();
        EditKMLButton = new javax.swing.JButton();
        StyleSplitterlButton = new javax.swing.JButton();
        KMLViewJPanel = new KMLParser.KMLViewJPanel();
        CalculatePointslButton = new javax.swing.JButton();
        KMLCalculatePoints = new KMLParser.KMLCalculatePoints();
        AboutjButton = new javax.swing.JButton();
        textlAddButton = new javax.swing.JButton();
        texAddtJPanel = new KMLParser.TextAddJPanel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KML Editor (v0.1.1 beta) by Pablo Anglat");

        OpenFileButton.setText("Open KML");
        OpenFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileButtonActionPerformed(evt);
            }
        });

        OpenedFilePathjLabel.setText("  Opened KML File: none");
        OpenedFilePathjLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        EditKMLButton.setText("Edit KML");
        EditKMLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditKMLButtonActionPerformed(evt);
            }
        });

        StyleSplitterlButton.setText("Style Splitter");
        StyleSplitterlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StyleSplitterlButtonActionPerformed(evt);
            }
        });

        CalculatePointslButton.setText("Calculate Points");
        CalculatePointslButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculatePointslButtonActionPerformed(evt);
            }
        });

        AboutjButton.setText("About");
        AboutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutjButtonActionPerformed(evt);
            }
        });

        textlAddButton.setText("Text Add");
        textlAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textlAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(KMLCalculatePoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KMLViewJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(parseByIconJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(texAddtJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OpenFileButton)
                        .addGap(101, 101, 101)
                        .addComponent(EditKMLButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StyleSplitterlButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CalculatePointslButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textlAddButton)
                        .addGap(106, 106, 106)
                        .addComponent(AboutjButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(OpenedFilePathjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 3225, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CalculatePointslButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AboutjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addComponent(textlAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(StyleSplitterlButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditKMLButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OpenFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(OpenedFilePathjLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KMLViewJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KMLCalculatePoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parseByIconJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(texAddtJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileButtonActionPerformed
        // TODO add your handling code here:

        JFileChooser fc = new JFileChooser();

        fc.addChoosableFileFilter(new KMLFilter());
        fc.setCurrentDirectory(new File("c:\\test\\"));

       // this.StatusBarjLabel.setText("  Open KML File");
        if (fc.showDialog(this, null) == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            this.kml = Kml.unmarshal(file);
            KML_ProblemsResolver.scaleProblem(kml);
            Document document = (Document) kml.getFeature();
            this.kmlStyleManager.setDocument(document);
            this.parseByIconJPanel.setKml(kml, file);
            this.parseByIconJPanel.setVisible(true);
            this.OpenedFilePathjLabel.setText("  Opened KML File:  " + file.getName() + "   in   " + file.getParent());
            this.EditKMLButton.setVisible(true);
            this.StyleSplitterlButton.setVisible(true);
            this.textlAddButton.setVisible(false);
            this.KMLViewJPanel.setVisible(true);
            this.parseByIconJPanel.setVisible(false);
            this.KMLViewJPanel.setKML(kml, this.kmlStyleManager, file);
            this.CalculatePointslButton.setVisible(true);
            this.KMLCalculatePoints.setVisible(false);
            this.KMLCalculatePoints.setKML(kml, kmlStyleManager, file);
            this.textlAddButton.setVisible(true);
            this.texAddtJPanel.setVisible(false);
            this.texAddtJPanel.setKML(kml, kmlStyleManager, file);
        }
        
    }//GEN-LAST:event_OpenFileButtonActionPerformed

    private void EditKMLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditKMLButtonActionPerformed
        // TODO add your handling code here:
        this.KMLViewJPanel.setVisible(true);
        this.parseByIconJPanel.setVisible(false);
        this.KMLCalculatePoints.setVisible(false);
        this.texAddtJPanel.setVisible(false);
    }//GEN-LAST:event_EditKMLButtonActionPerformed

    private void StyleSplitterlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StyleSplitterlButtonActionPerformed
        // TODO add your handling code here:
        this.KMLViewJPanel.setVisible(false);
        this.parseByIconJPanel.setVisible(true);
        this.KMLCalculatePoints.setVisible(false);
        this.texAddtJPanel.setVisible(false);
    }//GEN-LAST:event_StyleSplitterlButtonActionPerformed

    private void CalculatePointslButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculatePointslButtonActionPerformed
        // TODO add your handling code here:
        this.KMLViewJPanel.setVisible(false);
        this.parseByIconJPanel.setVisible(false);
        this.KMLCalculatePoints.setVisible(true);
        this.texAddtJPanel.setVisible(false);
    }//GEN-LAST:event_CalculatePointslButtonActionPerformed

    private void AboutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutjButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Created by Pablo Anglat\nMendoza, Argentina\npanglat@gmail.com\nhttp://www.panglat.com.ar/\n Version: 0.1.1 (beta) - November, 2010\nUsed Libraries:\n- Java API for KML\n   http://code.google.com/p/javaapiforkml/\n- Calculate distance, bearing and more between Latitude/Longitude points\n   Chris Veness - Movable Type Scripts\n   http://www.movable-type.co.uk/scripts/latlong.html\n- Java Geodesy Library for GPS – Vincenty’s Formula by Mike Gavaghan\n   http://www.gavaghan.org/blog/free-source-code/geodesy-library-vincentys-formula-java/", "About KML Editor v0.1.1 (beta)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_AboutjButtonActionPerformed

    private void textlAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textlAddButtonActionPerformed
        // TODO add your handling code here:
        
        this.KMLViewJPanel.setVisible(false);
        this.parseByIconJPanel.setVisible(false);
        this.KMLCalculatePoints.setVisible(false);
        this.texAddtJPanel.setVisible(true);
    }//GEN-LAST:event_textlAddButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutjButton;
    private javax.swing.JButton CalculatePointslButton;
    private javax.swing.JButton EditKMLButton;
    private KMLParser.KMLCalculatePoints KMLCalculatePoints;
    private KMLParser.KMLViewJPanel KMLViewJPanel;
    private javax.swing.JButton OpenFileButton;
    private javax.swing.JLabel OpenedFilePathjLabel;
    private javax.swing.JButton StyleSplitterlButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private KMLParser.ParseByIconJPanel parseByIconJPanel;
    private KMLParser.TextAddJPanel texAddtJPanel;
    private javax.swing.JButton textlAddButton;
    // End of variables declaration//GEN-END:variables

}
